- hosts: webserver
  tasks:
          - name: installing webserver
            package:
                    name: "httpd"
                    state: "present"

          - name: "install php"
            package:
                    name: "php"
                    state: "present"

          - name: "disable firewall"
            firewalld:
                    port: 8080/tcp
                    state: enabled
                    permanent: yes
                    immediate: yes
                    
          - name: "permissive selinux"
            selinux:
                    policy: targeted
                    state: permissive

          - name: "copying files from document root"
            copy:
                    src: "index.php"
                    dest: "/var/www/html/index.php"

          - name: "Starting webserver"
            service:
                    name: "httpd"
                    state: "restarted"
